"""
Config
"""

DEFAULT_ENV_NAME = 'CartPole-v0'
DEFAULT_NUM_ITERATIONS = 20000
DEFAULT_BATCH_SIZE = 512
DEFAULT_MAX_REPLAY_HISTORY = 100000
DEFAULT_GAMMA = 0.95
DEFAULT_EVAL_EPS = 10
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_CHECKPOINT_LOCATION = './checkpoints'
DEFAULT_MODEL_LOCATION = './model'

DEFAULT_RENDER_OPTION = 'collect'
RENDER_OPTIONS = ['none', 'collect']

DEFAULT_VERBOSITY_OPTION = 'progress'
VERBOSITY_OPTIONS = ['progress', 'loss', 'policy', 'init']

DEFAULT_VISUALIZER_TYPE = 'none'
VISUALIZER_TYPES = ['none', 'streamlit']

DEFAULT_PERSIST_PROGRESS_OPTION = 'all'
PERSIST_PROGRESS_OPTIONS = ['none', 'all']
