"""
Config
"""

DEFAULT_ENV_NAME = 'CartPole-v0'
DEFAULT_NUM_ITERATIONS = 20000
DEFAULT_BATCH_SIZE = 512
DEFAULT_MAX_REPLAY_HISTORY = 100000
DEFAULT_GAMMA = 0.95
DEFAULT_EVAL_EPS = 10
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_CHECKPOINT_LOCATION = './checkpoints'
DEAFULT_MODEL_LOCATION = './model'
